### ISSUE TITLE
Speech crackle with new Eloquence

### ISSUE THREAD

**Issue by munawarb** [pumper42nickel/eloquence_threshold#14]
I'm using NVDA 2020.1 and the newest release of the Eloquence add-on. I've noticed that the speech crackles occasionally. It usually happens towards the end of sentences. Otherwise this driver works well!

**Comment by Mohamed00** [comment]
Hi, can you try to see if the latest release fixes this?

**Comment by munawarb** [comment]
Yup, it seems to. Thanks for the fix!
