### ISSUE TITLE
NVDA freezes while bulk deleting emails in Microsoft Outlook 2021

### ISSUE THREAD

**Issue by alexstine** [pumper42nickel/eloquence_threshold#28]
Cross-posting from the NVDA main repo.

https://github.com/nvaccess/nvda/issues/13883

I have confirmed this is indeed related to the Eloquence add-on. All details can be found in the issue above including the full debug log of the traced error.

**Comment by lbk2907** [comment]
@alexstine
Have you try IBMTTS from David ACM?
You need to fine the Eloquence or IBM binary someware else for it to work.
The binary from this Eloquence Add-On should work.
I'll include the link down here.
Give it a try and update here whether the problem occur when using IBMTTS
or not.
I can't tested out because I not have install Microsoft Outlook.
If you need help, you can ask here or email me.
Thanks.
IBNTTS Driver: https://github.com/davidacm/NVDA-IBMTTS-Driver
My Email: lbk2907 at gmail dot com

**Comment by alexstine** [comment]
@lbk2907 Seems to be working for now. I will monitor the next couple days and see how it goes. What a weird issue...

Thanks.

**Comment by alexstine** [comment]
@lbk2907 Sadly, this did not fix it. I opened Outlook today and started scrolling the message list and ended up with another freeze plus nasty stack trace error for this add-on. 😞

**Comment by lbk2907** [comment]
@alexstine
May you open this issue on IBMTTS by David ACM as well?
Who knows they have the solution for that.

**Comment by lbk2907** [comment]
@alexstine
Attach the log as well.

**Comment by alexstine** [comment]
@lbk2907 A friend of mine reminded me about the following command.

```
outlook.exe /clearviews
```

I ran that from run dialog (Windows+R) and Outlook has been super fast ever sense. Must have been some type of messed up app data or something. Closing this out for now as I can no longer reproduce.

Thanks!

**Comment by alexstine** [comment]
@lbk2907 Okay, the issue is back. This sure is weird.

I have attached a new log in hopes you may spot an issue.

You will see that while deleting emails in Microsoft Outlook, a major freeze occurs in multiple libraries but it seems there is something going wrong in this add-on.

```
File "C:\Users\alexstineadmin\AppData\Roaming\nvda\addons\Eloquence\synthDrivers\_eloquence.py", line 233, in run
    func, args, kwargs = bgQueue.get()
File "C:\Users\alexstineadmin\AppData\Roaming\nvda\addons\Eloquence\synthDrivers\_eloquence.py", line 95, in run
    user32.GetMessageA(byref(msg), 0, 0, 0)
```

Anyway, after installing the IBMTTS add-on, do I need to configure it or is it just supposed to work? If I was supposed to configure it somehow, maybe that is why it did not work?

Thanks.

[nvda.log](https://github.com/pumper42nickel/eloquence_threshold/files/9127042/nvda.log)

**Comment by lbk2907** [comment]
@alexstine
You need to configure it.
Actually I have not use the Eloquence Add-On.
May you send me a message someware else so that I can send you the link along with the IBM binary?
You just need to install that and you can directly use it.
Email: lbk2907 at gmail dot com

**Comment by alexstine** [comment]
Seems this is an Outlook bug with emails that contain lots of graphics. Outlook itself is crashing, the screen reader just goes along for the ride. I finally managed to get it to break with JAWS today confirming it is not just NVDA or this add-on.

**Comment by lbk2907** [comment]
@alexstine
What you mean by is working now?
Are it work on this Eloquence Add-On or the IBMTTS Add-On from David ACM?

**Comment by alexstine** [comment]
@lbk2907 I have determined through testing this is an Outlook bug, not screen reader specific. You can also replicate some terrible lag in JAWS as well given the email is big enough with lots of graphics. Examples include email receipts from Uber. Those are the worst.

**Comment by lbk2907** [comment]
Thanks for the info.
